framework:
    charset:       UTF-8
    error_handler: null
    csrf_protection:
        enabled: true
        secret: xxxxxxxxxx
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: en
        lifetime:       3600
        auto_start:     false
        name:           symfony

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%


## Doctrine Configuration
#doctrine:
#   dbal:
#       default_connection:       default
#       connections:
#           default:
#               dbname:   xxxxxxxx
#               user:     xxxxxxxx
#               password: ~
#               logging:  %kernel.debug%
#   orm:
#       auto_generate_proxy_classes: %kernel.debug%
#       default_entity_manager:   default
#       entity_managers:
#           default:
#               connection: default
#               mappings:
#                   ZenstruckBundle: ~



